config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :tweets
  root to: "tweets#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,:username,:email,:password,:password_confirmation,:current_password)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
    <%end%>
    <% if flash[:alert]%>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <%end%>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Tweet App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/tweets/new">Create Tweet</a>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item dropdown text-right">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Update Profile", edit_user_registration_path, class: "dropdown-item"%>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
            </div>
          </li>
          <%else%>
          <li class="nav-item dropdown text-rigt">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Sign In", new_user_session_path, class: "dropdown-item"%>
              <%= link_to "Sign Up", new_user_registration_path ,class: "dropdown-item"%>
            </div>
          </li>
          <%end%>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<% if user_signed_in? %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name, class: "rounded-circle") %>
          </div>
          <div class="col-md-10">
            <%= render 'form'%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>

<div class="row">
  <div class="col-md-12">
    <% @tweets.each do |tweet| %>
    <br>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2 text-center">
            <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name, class: "rounded-circle") %><br><br>
            <% if user_signed_in? %>
            <p>
              <%= link_to tweet do%>
                <span><i class="fa fa-link" aria-hidden="true"></i></span>
              <%end%>
            </p>
            <p>
              <%= link_to edit_tweet_path(tweet) do%>
                <span><i class="fa fa-pencil" aria-hidden="true"></i></span>
              <%end%>
            </p>
            <p>
              <%= link_to tweet, method: :delete, data: { confirm: 'Are you sure?' } do%>
                <span><i class="fa fa-trash" aria-hidden="true"></i></span>
              <%end%>
            </p>
            <%end%>
          </div>
          <div class="col-md-10">
            <p>
              <strong><%= tweet.user.name %></strong><br>
              <span class="text-muted">@<%= tweet.user.username %></span>
            </p>
            <p><%= tweet.tweet.gsub(/^(.{400,}?).*$/m,'\1...') %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/tweets/_follow_suggestion.html.erb
<ul class="list-group">
  <li class="list-group-item active">Yoy may follow</li>
  <li class="list-group-item">
    <img src="https://via.placeholder.com/32x32" alt="img" class="rounded-circle">
    <strong>Jhon Doe</strong>
    <span class="text-muted">dummy@gamil.com</span>
  </li>
  <li class="list-group-item">
    <img src="https://via.placeholder.com/32x32" alt="img" class="rounded-circle">
    <strong>Jhon Doe</strong>
    <span class="text-muted">dummy@gamil.com</span>
  </li>
  <li class="list-group-item">
    <img src="https://via.placeholder.com/32x32" alt="img" class="rounded-circle">
    <strong>Jhon Doe</strong>
    <span class="text-muted">dummy@gamil.com</span>
  </li>
</ul>

app/views/tweets/_form.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.error_notification%>
  <%= f.input :tweet, placeholder: "Write a new tweet...", label: false, input_html: {rows: "4"} %>
  <div class="text-right">
    <%= f.button :submit, class: "btn btn-info btn-sm" %>
  </div>

<% end %>

app/views/tweets/_profile.html.erb
<div class="card">
  <div class="card-header bg-primary text-light">
    Featured
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4 text-center">
        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name, class: "rounded-circle") %>
      </div>
      <div class="col-md-8">
        <p style="padding-top: 10%">
          <strong><%= current_user.name %></strong><br>
          <span class="text-muted">@<%= current_user.username %></span>
        </p>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-md-4 text-center">
        <p><strong>Tweets</strong></p>
        <span class="text-success"><%= current_user.tweets.count%></span>
      </div>
      <div class="col-md-4 text-center">
        <p><strong>Followers</strong></p>
        <span class="text-info">125</span>
      </div>
      <div class="col-md-4 text-center">
        <p><strong>Following</strong></p>
        <span class="text-danger">221</span>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_trending.html.erb
<ul class="list-group">
  <li class="list-group-item active">Trending</li>
  <li class="list-group-item">Trending Item 1</li>
  <li class="list-group-item">Trending Item 2</li>
  <li class="list-group-item">Trending Item 3</li>
  <li class="list-group-item">Trending Item 4</li>
</ul>

app/views/tweets/edit.html.erb
<div class="container">
  <h2>Edit Your Tweet</h2>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>

</div>

app/views/tweets/index.html.erb
<div class="container-fluid" style="margin-top: 10px">
  <div class="row">
    <div class="col-md-3">
      <% if user_signed_in? %>
        <%= render 'profile'%>
      <%else%>
        <%= render 'trending'%>
      <%end%>
    </div>
    <div class="col-md-6">
      <%= render 'feed' %>
    </div>
    <div class="col-md-3">
      <%= render 'follow_suggestion' %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <h2>Create New Tweet</h2>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>

</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Tweet:</strong>
    <%= @tweet.tweet %>
  </p>

  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', tweets_path %>
</div>